### ISSUE TITLE
Figure out ratings

### ISSUE THREAD

**Issue by AaronMilne19** [AaronMilne19/team_project#14]

**Comment by PhilipZubel** [comment]
Using a javascript file (look how to set it up in city branch) and Ajax or js, create a method to add a instance of the CityRatings model. (You will need the current MVUser, the city, and the rating from 1 to 5)

**Comment by AaronMilne19** [comment]
I have managed to get the star buttons to create/update a rating object. Still need to figure out way to delete ratings and get the stars to show even after page is refreshed
